### ISSUE TITLE
документация

### ISSUE THREAD

**Issue by nika-gromova** [IamLena/trkpo#7]
найти способ документирования кода, описать в вики, по каким правилам документируем.

**Comment by nika-gromova** [comment]
@Alena-Kor , как там ?

**Comment by IamLena** [comment]
документацию к бд тоже

**Comment by nika-gromova** [comment]
https://www.youtube.com/watch?v=b4iFyrLQQh4

**Comment by Alena-Kor** [comment]
Документация в Wiki:
https://github.com/IamLena/trkpo/wiki/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F

**Comment by IamLena** [comment]
Так
в папке /docs в ветке develop лежат файлы для документации по sphinx
в /docs/_build/html есть index.html - 
![image](https://user-images.githubusercontent.com/34005469/117453728-f30d2680-af4d-11eb-8082-6c8e54b0d4c4.png)

Если добавляете документирующие комментарии в код к функциям, то надо все пересобрать следующим образом
удалить файлы из /docs/rst
перейти в папку .docs и выполить команды
sphinx-apidoc -o ./rst ../bot_srcs/database
sphinx-apidoc -o ./rst ../bot_srcs/handlers
sphinx-apidoc -o ./rst ../bot_srcs

Оно пропарсит наши питоновские файлики и создат в папке /str файлы типо .str которые нужны для генерации документации. Они подключаются потом в лежащие выше database, handler, modules, index.

теперь надо почистить папку _build/html. Можно ручками можно через make clean
потом нужно собрать html обратно
make html или sphinx-build -b html . _build/html

В лог он выдает ошибки но должен закончиться вот так "The HTML pages are in _build/html", а страничка index.html по тому же пути что и раньше должна работать.

Ошибки я так поняла вознимают из-за того, что sphinx пытается задокументировать подключаемую peewee. Как исправить не поняла, но похоже и так работает.

**Comment by IamLena** [comment]
устанавливала с помощью pip install sphinx на wsl
sphinx-quickstart --ext-autodoc вот так создала начальные настройки
